server:
  port: 8888

spring:
  application:
    name: openapi-yaml-reader

# OpenAPI配置
openapi:
  # 默认的OpenAPI文件路径
  file: classpath:openapi/example-api.yaml

logging:
  level:
    org.apache.camel.examples: INFO
